#%RAML 1.0
---

title: Compliance Cases
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json ]

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  correlationIDHeader: headers/CorrelationIDHeader.raml

/misc/compliance-cases:
  /case:
    post:
      displayName: create-case-api

      description: Passing Create Case data to integration framework

      is: [headers.acceptHeader, headers.contentHeader, correlationIDHeader.correlationID]

      (annotations.scope): "write:protect-connect"
      securedBy: [ sec.x-application: { scopes: [ "write:protect-connect" ] } ]
      body:
        application/json:
          type: !include schemas/CreateCaseSchema.json
          examples:
            example-1:
              description: example create repayment case body
              value: !include examples/CreateRepaymentCaseExampleRequest.json
            example-2:
              description: example create risk case body
              value: !include examples/CreateRiskCaseExampleRequest.json
      responses:
        202:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                example-1:
                  description: Submission has not passed validation. Invalid payload..
                  value:
                    code: INVALID_PAYLOAD
                example-2:
                  description: Submission has not passed validation. Missing header CorrelationId.
                  value:
                    code: MISSING_CORRELATION_ID
                example-3:
                  description: Submission has not passed validation. Invalid header CorrelationId.
                  value:
                    code: INVALID_CORRELATION_ID
                example-4:
                  description: An invalid value provided
                  value:
                    code: INVALID_FIELD
                example-5:
                  description: Invalid value in field
                  value:
                    code: MISSING_FIELD
                example-6:
                  description: Unexpected field found
                  value:
                    code: UNEXPECTED_FIELD
                example-7:
                  description: Invalid Json type as payload
                  value:
                    code: INVALID_JSON_TYPE
        401:
          body:
            application/json:
              type: types.errorResponse
              example:
                description: The credentials used are invalid.
                value:
                  code: UNAUTHORIZED
        422:
          body:
            application/json:
              type: types.errorResponse
              examples:
                example-1:
                  description: "Risk Case: Has to match with an existing Campaign ID in Caseflow"
                  value:
                    code: "101"
                example-2:
                  description: "Repayment Case: Repayment amount must be greater than 0"
                  value:
                    code: "101"
        500:
          body:
            application/json:
              type: types.errorResponse
              example:
                description: Internal server error.
                value:
                  code: INTERNAL_SERVER_ERROR
